import sys
import json
import re

sys.stdout.reconfigure(encoding='utf-8')

filepath = 'questions.js'

more_user_quiz_questions = [
    {
        "id": 70,
        "question": "A photodiode is normally operated under:",
        "options": [
            "Forward bias",
            "Reverse bias",
            "Zero bias",
            "Breakdown condition"
        ],
        "answer": 1,
        "explanation": "• Why 'Reverse bias' is Correct: Operating a photodiode under Reverse bias widens the depletion layer, creating a strong internal electric field that efficiently separates light-generated electron-hole pairs into photocurrent.\n• Why Other Choices are Incorrect: Forward bias allows heavy conventional current that masks light detection, while breakdown condition causes uncontrolled reverse avalanche."
    },
    {
        "id": 71,
        "question": "The output current of a photodiode is directly proportional to:",
        "options": [
            "Forward voltage",
            "Illumination intensity",
            "Junction temperature only",
            "Doping concentration"
        ],
        "answer": 1,
        "explanation": "• Why 'Illumination intensity' is Correct: Higher illumination intensity delivers more photons per second into the depletion region, generating a linearly proportional increase in free electron-hole pairs and output photocurrent.\n• Why Other Choices are Incorrect: Forward voltage is not applied during photodiode operation, while temperature and doping affect noise rather than linear light response."
    },
    {
        "id": 72,
        "question": "Dark current in a photodiode is:",
        "options": [
            "Reverse current with no light",
            "Forward current under strong light",
            "Current only at breakdown",
            "Peak current under illumination"
        ],
        "answer": 0,
        "explanation": "• Why 'Reverse current with no light' is Correct: Dark current is the minor reverse saturation current generated by ambient thermal energy when the photodiode is completely shielded from light.\n• Why Other Choices are Incorrect: It is a reverse leakage current (not forward), and occurs specifically under zero light illumination."
    },
    {
        "id": 73,
        "question": "The tunnel diode exhibits which unique property?",
        "options": [
            "Positive resistance",
            "Negative resistance",
            "Zero resistance",
            "Infinite resistance"
        ],
        "answer": 1,
        "explanation": "• Why 'Negative resistance' is Correct: On its forward V-I characteristic curve between the peak point and valley point, increasing the forward voltage reduces energy band overlap, causing current to fall as voltage increases (Negative Dynamic Resistance).\n• Why Other Choices are Incorrect: Standard resistors exhibit positive resistance where current increases with voltage."
    }
]

with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

new_q_str = ",\n" + json.dumps(more_user_quiz_questions, indent=6)[1:-1]

target = '"id": 69,'
if '"id": 70,' not in content:
    idx = content.find(target)
    if idx != -1:
        bracket_idx = content.find("}", idx)
        new_content = content[:bracket_idx+1] + new_q_str + content[bracket_idx+1:]
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(new_content)
        print(f"Successfully appended {len(more_user_quiz_questions)} new quiz questions (Q70-Q73) to basic_electronics in questions.js!")
    else:
        print("Could not locate target Q69.")
else:
    print("User quiz questions Q70-Q73 already present.")
