import sys
import json
import re

sys.stdout.reconfigure(encoding='utf-8')

filepath = 'questions.js'

ece_exam_questions = [
    {
        "id": 1,
        "question": "1. Statement: Germanium diodes begin conducting at a higher forward voltage threshold than Silicon diodes.",
        "options": [
            "a. True, because Germanium has a wider bandgap energy than Silicon.",
            "b. True, because Germanium exhibits lower thermal stability under direct current bias.",
            "c. False, because Germanium has a lower potential barrier compared to Silicon.",
            "d. False, because both materials possess identical potential barriers of 0.5 V at room temperature."
        ],
        "answer": 2,
        "explanation": "• Why Choice C is Correct: Germanium (Ge) has a lower barrier potential (approx 0.3 V) compared to Silicon (Si, approx 0.7 V). Therefore, Germanium begins conducting at a lower forward voltage threshold, making the statement False.\n• Why Other Choices are Incorrect: Germanium has a smaller bandgap (~0.67 eV vs Si 1.1 eV), and Germanium's potential barrier is 0.3 V, not equal to 0.7 V."
    },
    {
        "id": 2,
        "question": "2. Statement: Doping a semiconductor with trivalent impurities produces donor atoms that increase the concentration of free electrons.",
        "options": [
            "a. True, because trivalent atoms donate three extra electrons to the crystal lattice.",
            "b. True, because trivalent impurities increase total negative charge density.",
            "c. False, because trivalent impurities are acceptor atoms that create excess holes in P-type material.",
            "d. False, because trivalent impurities form metallic bonds that prevent current flow."
        ],
        "answer": 2,
        "explanation": "• Why Choice C is Correct: Trivalent impurities (e.g. Boron, Gallium, Indium) have 3 valence electrons and act as acceptor atoms that accept electrons to create excess holes, forming P-type material. Pentavalent impurities are donors that create free electrons.\n• Why Other Choices are Incorrect: Trivalent atoms create holes, not free electron donors."
    },
    {
        "id": 3,
        "question": "3. Statement: In the First Approximation (Ideal Diode Model), a forward-biased diode is treated as a closed switch with zero voltage drop.",
        "options": [
            "a. True, because the ideal model neglects the barrier potential and internal forward resistance.",
            "b. True, because ideal diodes convert all applied forward voltage directly into heat energy.",
            "c. False, because the ideal model includes a fixed 0.7 V battery drop across the terminals.",
            "d. False, because ideal diodes offer infinite resistance regardless of polarity."
        ],
        "answer": 0,
        "explanation": "• Why Choice A is Correct: The First Approximation (Ideal Diode) simplifies forward bias to a closed switch (V_D = 0 V, R_f = 0 Ω) and reverse bias to an open switch, completely neglecting barrier potential and internal resistance.\n• Why Other Choices are Incorrect: The ideal model has 0 V drop, unlike the practical second approximation which includes a 0.7 V drop."
    },
    {
        "id": 4,
        "question": "4. Statement: A reverse-biased practical diode permits zero electrical current to pass through its PN junction under all operational conditions.",
        "options": [
            "a. True, because the depletion region forms an absolute physical barrier to charge flow.",
            "b. True, because minority charge carriers cannot exist in P-type or N-type materials.",
            "c. False, because a very small reverse saturation leakage current flows due to thermally generated minority carriers.",
            "d. False, because forward current and reverse current are always equal in magnitude in PN junctions."
        ],
        "answer": 2,
        "explanation": "• Why Choice C is Correct: In reverse bias, a small reverse saturation leakage current (I_S) flows due to thermally generated minority carriers crossing the junction. Therefore, the statement claiming zero current is False.\n• Why Other Choices are Incorrect: Minority carriers are generated by thermal energy and produce reverse leakage current."
    },
    {
        "id": 5,
        "question": "5. Statement: The Second Approximation of a diode models the device as an ideal switch in series with a DC voltage source equal to its barrier potential.",
        "options": [
            "a. True, because it accounts for the threshold knee voltage required to initiate forward conduction while ignoring bulk resistance.",
            "b. True, because it includes the internal forward resistance alongside the junction capacitance.",
            "c. False, because the second approximation ignores barrier potential and only models internal resistance.",
            "d. False, because the second approximation applies strictly to reverse-bias operational calculations."
        ],
        "answer": 0,
        "explanation": "• Why Choice A is Correct: The Second Approximation (Practical Diode) models forward bias as a closed switch in series with a 0.7 V battery (for Si) or 0.3 V (for Ge), representing barrier knee voltage while omitting bulk resistance.\n• Why Other Choices are Incorrect: Bulk resistance is only added in the third approximation."
    },
    {
        "id": 6,
        "question": "6. Statement: The Third Approximation of a diode is also referred to as the Piecewise Linear Model.",
        "options": [
            "a. True, because it combines the barrier voltage with the internal forward resistance of the semiconductor.",
            "b. True, because it treats the diode as a variable AC voltage generator under steady-state DC conditions.",
            "c. False, because the piecewise linear model applies only to the First (Ideal) Approximation.",
            "d. False, because the third approximation assumes zero internal resistance during conduction."
        ],
        "answer": 0,
        "explanation": "• Why Choice A is Correct: The Third Approximation incorporates the threshold voltage V_D and internal bulk resistance r_f into a two-segment linear I-V curve, which is officially named the Piecewise Linear Model.\n• Why Other Choices are Incorrect: The piecewise linear model specifically includes internal resistance r_f."
    },
    {
        "id": 7,
        "question": "7. Statement: GaAs is a single-crystal elemental semiconductor like Silicon and Germanium.",
        "options": [
            "a. True, because GaAs is composed of a single element from Group IV of the periodic table.",
            "b. True, because GaAs possess identical electronic properties to pure Silicon crystals.",
            "c. False, because GaAs is a compound semiconductor made from Gallium and Arsenic.",
            "d. False, because GaAs is a synthetic ceramic insulator incapable of conducting current."
        ],
        "answer": 2,
        "explanation": "• Why Choice C is Correct: Gallium Arsenide (GaAs) is a Group III-V compound semiconductor formed chemically by Gallium and Arsenic, unlike Silicon and Germanium which are single-element single-crystal semiconductors.\n• Why Other Choices are Incorrect: GaAs is not a single element."
    },
    {
        "id": 8,
        "question": "8. Statement: Applying a forward bias to a PN junction diode lowers the internal potential barrier across the depletion region.",
        "options": [
            "a. True, because the external voltage opposes the built-in electric field, narrowing the depletion region.",
            "b. True, because the external voltage forces minority carriers to widen the depletion region.",
            "c. False, because forward biasing increases the internal potential barrier to prevent breakdown.",
            "d. False, because external voltage bias has no physical effect on depletion region width."
        ],
        "answer": 0,
        "explanation": "• Why Choice A is Correct: Forward bias applies positive voltage to the P-side and negative to the N-side, opposing the internal junction field, narrowing the depletion region, and lowering the barrier potential.\n• Why Other Choices are Incorrect: Reverse bias widens the depletion region, while forward bias thins it."
    },
    {
        "id": 9,
        "question": "9. Statement: Increasing the temperature of a semiconductor material increases its electrical resistance.",
        "options": [
            "a. True, because thermal vibration impairs covalent bonding, reducing the number of charge carriers.",
            "b. True, because semiconductors have a positive temperature coefficient of resistance like copper.",
            "c. False, because thermal energy generates additional electron-hole pairs, decreasing electrical resistance.",
            "d. False, because temperature changes affect electrical insulators exclusively."
        ],
        "answer": 2,
        "explanation": "• Why Choice C is Correct: Semiconductors have a Negative Temperature Coefficient (NTC). As temperature rises, thermal energy breaks covalent bonds and creates additional electron-hole pairs, increasing conductivity and decreasing resistance.\n• Why Other Choices are Incorrect: Metals have a positive temperature coefficient, but semiconductors have a negative temperature coefficient."
    },
    {
        "id": 10,
        "question": "10. Statement: Under zero bias conditions, an electrical current flows spontaneously through an isolated PN junction diode due to concentration gradients.",
        "options": [
            "a. True, because diffusion of majority carriers creates a continuous closed-loop direct current.",
            "b. True, because the built-in voltage acts as an internal DC power supply.",
            "c. False, because carrier diffusion is counterbalanced by drift current in equilibrium, resulting in zero net current.",
            "d. False, because charge carriers cannot move within semiconductor materials without external light exposure."
        ],
        "answer": 2,
        "explanation": "• Why Choice C is Correct: At thermal equilibrium (zero bias), the forward diffusion current of majority carriers is exactly equal and opposite to the reverse drift current of thermally generated minority carriers, making net current zero.\n• Why Other Choices are Incorrect: No net current flows without an external energy source."
    },
    {
        "id": 11,
        "question": "11. (Problem) A Silicon diode is connected in a simple series circuit with a 1.2 kΩ load resistor and a DC source V_S = 12 V. Using the Second Approximation, calculate the total circuit current I_D in milliamperes (mA).",
        "options": [
            "a. 9.4167 mA",
            "b. 10.0 mA",
            "c. 8.8333 mA",
            "d. 9.15 mA"
        ],
        "answer": 0,
        "explanation": "• Why '9.4167 mA' is Correct: By the Second Approximation, Silicon forward voltage V_D = 0.7 V. Voltage across load resistor V_R = V_S - V_D = 12 V - 0.7 V = 11.3 V. By Ohm's Law, I_D = V_R / R_L = 11.3 V / 1200 Ω = 0.00941667 A = 9.4167 mA.\n• Why Other Choices are Incorrect: 10.0 mA assumes an ideal diode (12 V / 1200 Ω), while 8.8333 mA assumes an incorrect drop."
    },
    {
        "id": 12,
        "question": "12. (Problem) For the same series circuit described in Item 11 (V_S = 12 V, Silicon diode V_D = 0.7 V, R_L = 1.2 kΩ, I_D = 9.4167 mA), calculate the power dissipated by the Silicon diode (P_D) in milliwatts (mW) using the Second Approximation.",
        "options": [
            "a. 7.1 mW",
            "b. 6.5917 mW",
            "c. 6.1833 mW",
            "d. 8.4 mW"
        ],
        "answer": 1,
        "explanation": "• Why '6.5917 mW' is Correct: Power dissipated by diode P_D = V_D * I_D = 0.7 V * 9.416667 mA = 6.591667 mW ≈ 6.5917 mW.\n• Why Other Choices are Incorrect: 7.1 mW and 6.1833 mW use incorrect current or voltage values."
    },
    {
        "id": 13,
        "question": "13. (Problem) A Germanium diode exhibits an internal forward resistance r_f = 15 Ω. It is connected in series with a load resistor R_L = 470 Ω and a 9 V DC supply. Using the Third Approximation, calculate the total current in milliamperes (mA).",
        "options": [
            "a. 18.5106 mA",
            "b. 17.9381 mA",
            "c. 19.1489 mA",
            "d. 17.3913 mA"
        ],
        "answer": 1,
        "explanation": "• Why '17.9381 mA' is Correct: Third Approximation for Germanium: V_D = 0.3 V, internal resistance r_f = 15 Ω. Total circuit resistance R_total = r_f + R_L = 15 Ω + 470 Ω = 485 Ω. Current I = (V_S - V_D) / R_total = (9 V - 0.3 V) / 485 Ω = 8.7 V / 485 Ω = 0.01793814 A = 17.9381 mA.\n• Why Other Choices are Incorrect: 18.5106 mA ignores internal resistance r_f (8.7 V / 470 Ω)."
    },
    {
        "id": 14,
        "question": "14. (Problem) Using the parameters and results from Item 13 (V_S = 9 V, Germanium V_D = 0.3 V, r_f = 15 Ω, R_L = 470 Ω, I = 17.9381 mA), calculate the actual terminal voltage drop across the Germanium diode in volts using the Third Approximation.",
        "options": [
            "a. 0.3 V",
            "b. 0.5691 V",
            "c. 0.2691 V",
            "d. 0.45 V"
        ],
        "answer": 1,
        "explanation": "• Why '0.5691 V' is Correct: Actual diode terminal voltage V_terminal = V_D + (I * r_f) = 0.3 V + (0.01793814 A * 15 Ω) = 0.3 V + 0.269072 V = 0.569072 V ≈ 0.5691 V.\n• Why Other Choices are Incorrect: 0.3 V is only the knee voltage without internal resistance voltage drop."
    },
    {
        "id": 15,
        "question": "15. (Problem) A Gallium Arsenide (GaAs) diode (V_F = 1.2 V) is connected across a 15 V DC source in series with a 2.2 kΩ resistor. Using the Second Approximation, determine the voltage across the load resistor V_L in volts (V).",
        "options": [
            "a. 15 V",
            "b. 13.8 V",
            "c. 1.2 V",
            "d. 14.3 V"
        ],
        "answer": 1,
        "explanation": "• Why '13.8 V' is Correct: GaAs forward barrier voltage V_F = 1.2 V. By Kirchhoff's Voltage Law, voltage across load resistor V_L = V_S - V_F = 15 V - 1.2 V = 13.8 V.\n• Why Other Choices are Incorrect: 15 V neglects diode drop, 1.2 V is the diode drop itself, and 14.3 V assumes 0.7 V drop."
    },
    {
        "id": 16,
        "question": "16. (Problem) Two identical Silicon diodes are connected in series with a 680 Ω load resistor and a 10 V DC voltage supply. Using the Second Approximation, calculate the total circuit current in milliamperes (mA).",
        "options": [
            "a. 13.6765 mA",
            "b. 12.6471 mA",
            "c. 14.7059 mA",
            "d. 11.6176 mA"
        ],
        "answer": 1,
        "explanation": "• Why '12.6471 mA' is Correct: Two series Silicon diodes drop V_total = 2 * 0.7 V = 1.4 V. Resistor voltage V_R = 10 V - 1.4 V = 8.6 V. Circuit current I = 8.6 V / 680 Ω = 0.01264706 A = 12.6471 mA.\n• Why Other Choices are Incorrect: 13.6765 mA counts only one diode drop (9.3 V / 680 Ω)."
    },
    {
        "id": 17,
        "question": "17. (Problem) For a series circuit with a 10 V DC source and a single Silicon diode (V_D = 0.7 V) connected across a 330 Ω load resistor, calculate the load voltage V_L across the 330 Ω resistor in volts (V).",
        "options": [
            "a. 9.3 V",
            "b. 4.3 V",
            "c. 10.0 V",
            "d. 7.9 V"
        ],
        "answer": 0,
        "explanation": "• Why '9.3 V' is Correct: By KVL, load voltage V_L = V_S - V_D = 10 V - 0.7 V = 9.3 V.\n• Why Other Choices are Incorrect: 4.3 V corresponds to a 5 V source (5 V - 0.7 V), while 10.0 V ignores diode barrier drop."
    },
    {
        "id": 18,
        "question": "18. (Problem) Two Silicon diodes are connected in parallel with each other in the forward direction. This parallel branch is placed in series with a 330 Ω resistor and a 5 V DC supply. Assuming equal current sharing, calculate the current through each individual diode in milliamperes (mA) using the Second Approximation.",
        "options": [
            "a. 13.0303 mA",
            "b. 6.5152 mA",
            "c. 7.5758 mA",
            "d. 3.2576 mA"
        ],
        "answer": 1,
        "explanation": "• Why '6.5152 mA' is Correct: Parallel Silicon diodes clamp the branch voltage to V_D = 0.7 V. Resistor voltage V_R = 5 V - 0.7 V = 4.3 V. Total supply current I_total = 4.3 V / 330 Ω = 13.0303 mA. Since current divides equally between two parallel diodes: I_diode = 13.0303 mA / 2 = 6.51515 mA ≈ 6.5152 mA.\n• Why Other Choices are Incorrect: 13.0303 mA is total circuit current before dividing by 2."
    },
    {
        "id": 19,
        "question": "19. (Problem) An ideal Silicon diode is connected in reverse bias across a 24 V DC supply in series with a 1 kΩ resistor. Calculate the terminal voltage across the reverse-biased diode V_D in volts (V).",
        "options": [
            "a. 0 V",
            "b. 24 V",
            "c. 12 V",
            "d. 0.7 V"
        ],
        "answer": 1,
        "explanation": "• Why '24 V' is Correct: In reverse bias, an ideal diode acts as an open circuit (I = 0). With zero current flowing through the resistor (V_R = 0 V), the full 24 V supply voltage drops across the open diode terminals.\n• Why Other Choices are Incorrect: 0 V occurs across an ideal diode in forward bias, not reverse bias."
    },
    {
        "id": 20,
        "question": "20. (Problem) A Silicon diode and a Germanium diode are connected in parallel (facing the same forward conduction path) in series with a 1.5 kΩ load resistor and a 12 V DC source. Using the Second Approximation, determine the total current drawn from the supply in milliamperes (mA).",
        "options": [
            "a. 7.5333 mA",
            "b. 7.8000 mA",
            "c. 7.2667 mA",
            "d. 8.0000 mA"
        ],
        "answer": 1,
        "explanation": "• Why '7.8000 mA' is Correct: Germanium turns ON at 0.3 V, which is lower than Silicon's 0.7 V threshold. Germanium conducts first and clamps the node voltage to 0.3 V, keeping Silicon OFF. Resistor voltage V_R = 12 V - 0.3 V = 11.7 V. Total current I = 11.7 V / 1500 Ω = 0.0078 A = 7.8 mA.\n• Why Other Choices are Incorrect: 7.5333 mA assumes Silicon conducts (11.3 V / 1500 Ω = 7.533 mA), but Silicon remains OFF."
    }
]

with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

# 1. Add dedicated ece_prelim_exam pool to SUBJECT_DATA
exam_pool_obj = {
    "title": "ECE 005 Prelim Exam (TIP 2026)",
    "chapter": "Prelim Exam",
    "questions": ece_exam_questions
}
exam_pool_json = json.dumps(exam_pool_obj, indent=4)

if '"ece_prelim_exam":' not in content:
    # Insert right before basic_electronics inside SUBJECT_DATA = {
    insert_target = 'var SUBJECT_DATA = {'
    idx = content.find(insert_target)
    if idx != -1:
        insert_pos = idx + len(insert_target)
        new_content = content[:insert_pos] + "\n  ece_prelim_exam: " + exam_pool_json + ",\n" + content[insert_pos:]
        content = new_content
        print("Successfully added dedicated ece_prelim_exam subject pool to SUBJECT_DATA!")

# 2. Append Q117-Q136 to basic_electronics pool in questions.js
basic_elec_questions = []
for q in ece_exam_questions:
    new_q = dict(q)
    new_q["id"] = q["id"] + 116 # ID 117 to 136
    basic_elec_questions.append(new_q)

b_q_str = ",\n" + json.dumps(basic_elec_questions, indent=6)[1:-1]
target_b = '"id": 116,'

if '"id": 117,' not in content:
    idx_b = content.find(target_b)
    if idx_b != -1:
        bracket_idx = content.find("}", idx_b)
        content = content[:bracket_idx+1] + b_q_str + content[bracket_idx+1:]
        print("Successfully appended Q117-Q136 to basic_electronics pool!")

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(content)

print("questions.js successfully updated!")
